name: Lint and test

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: 3.6.7
          poetry_version: 0.12.17
          working_directory: ./working_dir # Optional, defaults to '.'
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.1.0
        with:
          python_version: 3.6.7
          poetry_version: 0.12.17
          working_directory: ./working_dir
          args: run python -m pytest --cov=src --cov-branch --cov-fail-under=95 tests/
